# Site settings
title: "Socialkardia"
description: "Digital social awareness tools."
owner: "Kurtis Rainbolt-Greene"
github: "http://github.com/socialkardia/socialkardia.github.io"
logo: "http://github.com/socialkardia.png"
analytics: UA-18715035-11
profiles:
  -
    name: "Twitter"
    url: "http://twitter.com/socialkardia"
  -
    name: "Github"
    url: "http://github.com/socialkardia"
links:
  -
    name: "About"
    url: "/about"
  -
    name: "Policy"
    url: "/Policy"
  -
    name: "Contact"
    url: "/contact"
  -
    name: "Socialkardia"
    url: "/"
    css: "brand header"
  -
    name: "Radar"
    url: "/radar"
  -
    name: "Monitor"
    url: "/monitor"
  -
    name: "API"
    url: "/api"

# Build settings
markdown: redcarpet
permalink: /:title/
exclude:
  - Gemfile
  - LICENSE
  - README.md
  - CNAME
  - .ruby-gemset
  - .ruby-version
  - .gitignore
